### ISSUE TITLE
many authors' IPNS failed to attach articles (since applied tc traffic control)

### ISSUE THREAD

**Issue by tx0c** [thematters/developer-resource#222]
when active IPFS node is under tc (traffic control), it has a high (70%+) chance failed to operate with IPNS:

```
2023-05-17T01:06:11.952Z importKey ERROR: FetchError: invalid json response body at http://ipfs.prod.vpc:5001/api/v0/key/import?arg=for-flow1978-92827a09-2ae2-4e11-b8e8-0ce1e877da30&format=pem-pkcs8-cleartext reason: Unexpected end of JSON input
    at /var/app/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IPFSServer.importKey (/var/app/build/connectors/ipfs/index.js:35:34)
    at async ArticleService.publishFeedToIPNS (/var/app/build/connectors/articleService.js:163:38) {
  type: 'invalid-json'
} false Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    connection: [ 'Close' ]
  }
}
2023-05-17T01:06:11.978Z start update IPNSRec: {
  id: '6824',
  userId: '97967',
  ipnsKey: 'k51qzi5uqu5dkrfah5ury7j07v5zy5av15yyf35bpnv051lfs2bqixpr9z7at9',
  lastDataHash: 'Qmcw6a7M2Ka8AM2dKVoaJqsivm6ZuAD13jutU8tgEwJiVh',
  createdAt: 2022-11-16T01:34:14.495Z,
  updatedAt: 2023-05-17T01:06:11.977Z,
  lastPublished: 2023-05-16T02:06:20.434Z
}
2023-05-17T01:06:11.989Z publishFeedToIPNS last ERROR: TypeError: Cannot read properties of undefined (reading 'addAll')
    at ArticleService.publishFeedToIPNS (/var/app/build/connectors/articleService.js:233:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  ipnsKey: 'k51qzi5uqu5dkrfah5...pnv051lfs2bqixpr9z7at9',
  kname: 'for-flow1978-92827a09-2ae2-4e11-b8e8-0ce1e877da30',
  directoryName: 'for-flow1978-92827a09-2ae2-4e11-b8e8-0ce1e877da30-with-393087-比特韭手2023-5-17@2023-05-17T01',
  userName: 'flow1978'
}
```

**Comment by tx0c** [comment]
switch to use Photon storage gw3 API instead.
